export const blogArticles = [
  {
    slug: "understanding-cargo-insurance-basics",
    title: "Understanding Cargo Insurance: A Complete Guide",
    excerpt: "Essential insights into cargo insurance coverage, claims, and risk management for international shipments.",
    category: "risk",
    date: "2024-01-15",
    readTime: "6 min read",
    image: "/cargo.jpg",
    tags: ["insurance", "risk-management", "shipping"],
    author: "Kovasure Team",
  },
  {
    slug: "marine-insurance-coverage-explained",
    title: "Marine Insurance Coverage Explained",
    excerpt: "Learn about different types of marine insurance coverage and how to choose the right protection for your cargo.",
    category: "industry",
    date: "2024-01-10",
    readTime: "5 min read",
    image: "/ship.jpeg",
    tags: ["marine-insurance", "coverage", "protection"],
    author: "Kovasure Team",
  },
  {
    slug: "global-trade-risk-management",
    title: "Effective Risk Management in Global Trade",
    excerpt: "Strategies to mitigate risks in international shipping and protect your business interests.",
    category: "global",
    date: "2024-01-05",
    readTime: "7 min read",
    image: "/portview.jpg",
    tags: ["risk-management", "global-trade", "strategy"],
    author: "Kovasure Team",
  },
  {
    slug: "cargo-insurance-claims-process",
    title: "How to File a Cargo Insurance Claim",
    excerpt: "Step-by-step guide to filing cargo insurance claims and ensuring successful reimbursement.",
    category: "risk",
    date: "2023-12-28",
    readTime: "5 min read",
    image: "/risk.jpg",
    tags: ["claims", "insurance", "process"],
    author: "Kovasure Team",
  },
  {
    slug: "compliance-international-shipping",
    title: "Compliance Requirements for International Shipping",
    excerpt: "Navigate complex compliance regulations and ensure your shipments meet international standards.",
    category: "compliance",
    date: "2023-12-20",
    readTime: "8 min read",
    image: "/complaince.jpg",
    tags: ["compliance", "regulations", "international"],
    author: "Kovasure Team",
  },
  {
    slug: "cargo-insurance-technology-trends",
    title: "Technology Trends Transforming Cargo Insurance",
    excerpt: "Discover how digital innovation is reshaping cargo insurance and streamlining claims processing.",
    category: "industry",
    date: "2023-12-15",
    readTime: "6 min read",
    image: "/shipment.jpg",
    tags: ["technology", "innovation", "digital"],
    author: "Kovasure Team",
  },
];
